# Permalinks
permalink: /:title

# Setup
title: Run Through
tagline: 'The Notes'
description: 'Computer Science and Engineering concepts.'
url: https://runthrough.github.io/
baseurl: ''

collections_dir: cols
collections:
    concepts:
        output: true
        permalink: /:title
    languages:
        output: true
        permalink: /:title
    statistics:
        output: true
        permalink: /:title
    practice:
        output: true
        permalink: /:title
    de:
        output: true
        permalink: /:title
    devops:
        output: true
        permalink: /:title
    runs:
        output: true
        permalink: /:title

author:
    name: 'Run Through'
    url: https://runthrough.github.com

# Custom vars
version: 1.0.0
conf:
    look: ''
    circular_pagination: true
    default_collection: 'concepts'
    highlight_style: # railscasts, agate, github-gist
        light: 'github-gist'
        dark: 'agate'

github:
    repo: https://github.com/runthrough/runthrough.github.io
    username: 'runthrough'
    gist_url: https://gist.githubusercontent.com/
    gist_id:
        concepts: 9950382bef6c683ca1780159a286f88c
        languages: 7944c2884eb2c8f6e467facfef731de2
        statistics: 5caa6172beb8828ef496f478dbaef0c8
        practice: a4a996b58c08535eeca8746872e878d3
        de: cb7128606f8f321b139c704166b03821
        devops: abdb481438b958217e67a596a3332881
        runs: 1a69cff1c4ebce245820706be0a695c2

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE.md
    - README.md