# Dependencies
markdown: redcarpet
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Run Through
tagline: 'The Notes.'
description: 'Computer Science and Engineering concepts.'
url: https://runthrough.github.io/
baseurl: ''

author:
    name: 'Run Through'
    url: http://runthrough.com

paginate: 5

# Custom vars
version: 1.0.0
look: ''

github:
    repo: https://github.com/runthrough/runthrough.github.io
