# Permalinks
permalink: pretty

# Setup
title: Run Through
tagline: 'The Notes'
description: 'Computer Science and Engineering concepts'
url: https://runthrough.github.io/
baseurl: ''

author:
    name: 'Run Through'
    url: https://runthrough.github.com

# Custom vars
version: 1.0.0
look: ''
gist_url: https://gist.githubusercontent.com/
gist_username: 'runthrough'
gist_id: 9950382bef6c683ca1780159a286f88c

github:
    repo: https://github.com/runthrough/runthrough.github.io