# Permalinks
permalink: pretty

# Setup
title: Run Through
tagline: 'The Notes'
description: 'Computer Science and Engineering concepts'
url: https://runthrough.github.io/
baseurl: ''

author:
    name: 'Run Through'
    url: https://runthrough.github.com

# Custom vars
version: 1.0.0
conf:
    look: ''
    cpg: true

github:
    repo: https://github.com/runthrough/runthrough.github.io
    username: 'runthrough'
    gist_url: https://gist.githubusercontent.com/
    gist_id: 9950382bef6c683ca1780159a286f88c

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE.md
    - README.md